x-php-build: &app-base
  image: arome-php:local
  env_file:
    - .env
  networks:
    - arome_network
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_healthy

services:
  php:
    <<: *app-base
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: app
    container_name: arome_app
    environment:
      RUN_MIGRATIONS: "true"
    user: www-data
    restart: unless-stopped

  scheduler:
    <<: *app-base
    container_name: arome_scheduler
    user: www-data
    command: php artisan schedule:work
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: arome_nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - arome_network

  db:
    image: postgres:16.14-alpine
    container_name: arome_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [arome_network]

  redis:
    image: redis:8.10-alpine
    container_name: arome_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks: [arome_network]

  artisan:
    <<: *app-base
    entrypoint: ["php", "/var/www/laravel/artisan"]
    user: www-data
    profiles: ["tools"]
    restart: "no"

networks:
  arome_network:
    driver: bridge
  proxy_net:
    external: true

volumes:
  db_data:
  redis_data:
